### ISSUE TITLE
skate.js.org unusable in Safari

### ISSUE THREAD

**Issue by thepian** [skatejs/skatejs.github.io#13]
When I visit the site I get a nearly blank page.

**Comment by treshugart** [comment]
That's because safari released a broken shadow DOM implementation and doesn't really care that they did.

**Comment by treshugart** [comment]
We've tried overriding it with the polyfills but that's still kinda buggy.

**Comment by treshugart** [comment]
I'm not sure what to do. I reported the issue to Webkit prior to release and they still did it. Tech preview, once in stable should fix it but you're waiting for the next update unfortunately.
