### ISSUE TITLE
Tabs titles re-render doesn't work in IE, FF

### ISSUE THREAD

**Issue by Hotell** [skatejs/skatejs.github.io#14]
- this is probably because non native browsers doesn't trigger property changes in slotted elements, so no slotchange is triggered
![skate-tab-titles-bug](https://cloud.githubusercontent.com/assets/1223799/22169687/4cd82568-df76-11e6-840c-a2811c436468.gif)

**Comment by treshugart** [comment]
The polyfill should be filling that, though.
