### ISSUE TITLE
Docs for Renderers and Utilities broken

### ISSUE THREAD

**Issue by mraerino** [skatejs/skatejs.github.io#19]
Currently these and their children pages return a 404:
- http://skatejs.netlify.com/renderers
- http://skatejs.netlify.com/utilities

**Comment by treshugart** [comment]
Yeah, the site is a WIP of the 5.x branch. I've been working a lot on it, though! It's being released from the main skatejs/skatejs repo under the `site/` directory. I'll close this. Can raise issues directly against the skate repo.

**Comment by mraerino** [comment]
Maybe put a deprecated tag on this repo?

**Comment by treshugart** [comment]
Good idea!
