### ISSUE TITLE
styles missing safari 10.0 (desktop and mobile)

### ISSUE THREAD

**Issue by jimmont** [skatejs/skatejs.github.io#7]
For Safari version 10.0 on both desktop and mobile the css styles are not being applied. Should this issue be reported in [`skatejs`](https://github.com/skatejs/skatejs/) or here?

**Comment by treshugart** [comment]
Unfortunately it's because of a pretty bad bug in Safari https://bugs.webkit.org/show_bug.cgi?id=160331. Haven't got around to fixing it yet.

**Comment by treshugart** [comment]
Fixed. See https://github.com/skatejs/skatejs/issues/836#issuecomment-254052365.
