### ISSUE TITLE
Site doesn't render in Firefox 49

### ISSUE THREAD

**Issue by mwcz** [skatejs/skatejs.github.io#9]
In Firefox 49 (current stable release), the site doesn't render.  There's a JS error, `TypeError: ce.get is not a function`.

![screenshot from 2016-10-10 11-35-49](https://cloud.githubusercontent.com/assets/364615/19241698/d5f76e06-8edd-11e6-9f74-7ba2369fe2b3.png)

**Comment by treshugart** [comment]
Thanks, @mwcz. Seems https://github.com/skatejs/web-components/issues/18 is the probably cause here. Need to investigate, though.

**Comment by treshugart** [comment]
Fixed. See https://github.com/skatejs/skatejs/issues/836#issuecomment-254052365.

**Comment by treshugart** [comment]
This was also fixed in skatejs-web-components by forcing webpack to do the build instead of rollup.

**Comment by mwcz** [comment]
:+1: works for me!
